server:
    port: 8080
    error:
      path: /error
spring:
  thymeleaf:
    suffix: .html
    cache: false
    encoding: UTF-8
    prefix:  classpath:/templates/
  redis:
    timeout: 2000ms
    host: 127.0.0.1
    port: 6379
  profiles:
        active: prod
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sakila?useSSL=true&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 133309
  jpa:
      hibernate:
        ddl-auto: create
      show-sql: true

mybatis:
  mapper-locations: classpath:mapper/CityMapper.xml
  type-aliases-package: com.wx.springboot_docker.domain.City



