server:
    port: 8080
    error:
      path: /error
spring:
  thymeleaf:
    suffix: .html
    cache: false
    encoding: UTF-8
    prefix:  classpath:/templates/
  redis:
    timeout: 2000ms
    host: redis
    port: 6379
  profiles:
        active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/persontest?characterEncoding=utf8
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: create
      show-sql: true

mybatis:
  mapper-locations: classpath:mapper/UserMapper.xml
  type-aliases-package: com.wx.springboot_docker.domain.User



